name: anaconda-client-env
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pylint
  - python=3.8
  - tensorflow-gpu=2.3
  - autopep8
  - shap
  - matplotlib
  - tensorflow==2.3=mkl_py38h1fcfbd6_0