name: Main

on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v1
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false
    - run: python -m unittest discover
      name: tests
    - run: pylint -d "R,C" src tests
      name: lint